{% set version = "0.5.0" %}

package:
  name: branca
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/branca/branca-{{ version }}.tar.gz
  sha256: e6f2f7eba7dd368ceef8f63822b867f5e11d4d3abdd099a787db9ed2b7065ae1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - setuptools
    - jinja2
    - six

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - branca

about:
  home: https://github.com/python-visualization/branca
  license: MIT
  license_file: LICENSE.txt
  summary: This library is a spinoff from folium with the non-map-specific features

extra:
  recipe-maintainers:
    - BibMartin
    - ocefpaf
