{% set version = "0.3.1" %}

package:
  name: branca
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/branca/branca-{{ version }}.tar.gz
  sha256: 3e762c9bdf40725f3d05ea1fda8fae9b470bfada6474e43a1242c8204a7bb15e

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - setuptools
    - jinja2
    - six

test:
  imports:
    - branca

about:
  home: https://github.com/python-visualization/branca
  license: MIT
  license_file: LICENSE.txt
  summary: 'This library is a spinoff from folium with the non-map-specific features'

extra:
  recipe-maintainers:
    - BibMartin
    - ocefpaf
