{% set name = "branca" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/branca-{{ version }}.tar.gz
    sha256: ac397c2d79bd13af0d04193b26d5ed17031d27609a7f1fab50c438b8ae712390
  - url: https://github.com/python-visualization/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: b6ec0bc22418198f8ef1ad1b1bc459472120aa1199acf077cab763cf9265436e
    folder: gh

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools >=41.2
    - setuptools_scm
  run:
    - python
    - jinja2 >=3

test:
  source_files:
    - gh/tests
  imports:
    - branca
    - branca.colormap
    - branca.element
    - branca.utilities
  requires:
    - pip
    - pytest
    - selenium
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    # test_utilities -> problem with path: FileNotFoundError: [Errno 2] No such file or directory: '$SRC_DIR/gh/tests/../branca/_schemes.json'
    - pytest -v gh/tests --ignore="gh/tests/test_utilities.py"

about:
  home: https://github.com/python-visualization/branca
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: This library is a spinoff from folium with the non-map-specific features
  description: |
    This library is a spinoff from folium with the non-map-specific features.
    It can be used to generate HTML + JS. It is based on Jinja2.
  doc_url: https://python-visualization.github.io/branca
  dev_url: https://github.com/python-visualization/branca

extra:
  recipe-maintainers:
    - BibMartin
    - ocefpaf