{% set name = "branca" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/branca-{{ version }}.tar.gz
  sha256: 55949855214504c7583b71b9a03a84dce2e96a84027613bb53b42d04844ce24e

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - wheel
  run:
    - python
    - jinja2

test:
  imports:
    - branca
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/python-visualization/branca
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: This library is a spinoff from folium with the non-map-specific features
  description: |
    This library is a spinoff from folium with the non-map-specific features.
    It can be used to generate HTML + JS. It is based on Jinja2.
  doc_url: https://python-visualization.github.io/branca/
  dev_url: https://github.com/python-visualization/branca

extra:
  recipe-maintainers:
    - BibMartin
    - ocefpaf
