travis:
  secure:
    BINSTAR_TOKEN: s6S1U5rcXrbMPDbOymaQIlSzK3JTm7RgDv7nzVP5uAC/hxNfEfLgcy8B6nFIWWbL2qu1d42xHXLtFbllGt2Zwv0woHzG2dvbFUwCBQCbzcbj3CgKpgpZmcd2Ilst0JgZmDttkXEXSuByhrVQMcjCK6zLM5F8B3dzZwhHfjjXDFWOYRPhjfwDohF9kdAHskc2+B4/BoI8BsbUzXABeUNshhuz117T59qiMPV/GdDpKyjRHUThneEr20PPbk0kcdeh90xJ5VB9lsuJZghUjHy1TDqkqi7i1z9E+epnd/RZldiDTKG6ca5qJkMf+d4BxVvWECY81V3zG0qY+itOiVk9ZBsUOYM8VULSZtD3neEtE/jfeDhBBqEkuVjvRZ84lYjGoIvsQaDRjZ6I/QZ8/zMm7BDY/+zig170TVb9gwA9TbluviRyFZGvAxAvFvZiB/Xcl3zXKDCBpI6NEG5mSSSb+dgbHjBZMQyLabLb144SqU7Rdm51LVXQweXglMYG89bUZrGH9mFyHI+ACUg6RAdZTTZewpxzYTZ2TrPWWcfWfuGeZEQEZCzvBhrtpVvmLEUGvhzkodX6vLuoq1N1g2TVw8z6OgNq+exY6pWQ/BGpuiOZV8STD/PWBu2YTDq8FWA/JwyE1RrgJIsfJhHLqM8h9gKk63JcRIMo7NR9y893otg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
