travis:
  secure:
    BINSTAR_TOKEN: HASuAQWaIVpAOVAGWPgoIYQ4rh1IWeMmzcp9+P2BhWcztDWkoOJl9pfmGILZPd2CjtSZTWCc3bAgBZ27KWPJqN8WXTQmKWuXI568DFBnwXv6T0WMsnpDW8MLgJPsbAW9Lh90YhWkLAPZsUy57JaadzpKXQLNR9bcSlfgdtog3/d5U8Lx93ie9P54k50RPQlPiGbvdV10c67anXM/woyHKaFNbI2SIWjNNs/uvcd2Fyw89SF5iFWBegt+m02GxfhFwT2fLrBF6hlYcAKEzOu8Pq36+t9+USfBTvyy39qEoaHZuIBk/ZAj5C7LMdt9AVdzdBDmz1fXBU0VJ/iP/gqGHIWl4FzHpkdR4BjB3827IU4Cd7VmOG5EIKu7S/eIXAz/CjW1In3/SRjfCBSQ63JHxHUKF7xzw1tvsA9z3f2iIcCNsmZz0BgCDpw8Tn7lu7Tt00q8el4ix96jd13JBL6/yE+uuUQ8cbIx9r4pLCmxJcOI76C135qP4mnWxvIOI1NB0j9iRK6Ux8FdHR5QLzooRg7+lGfJ/v9K6keARQCVa2L6xm3AnJeYxqOGNOpMNrQsbebyWoXrCypwIRDj1bS3ghY/mTHc+w091H0KkOW04ZxiywGAXh7YwI/AcoLpu/bgIAErIYbMwsARDmk3+FTSUREzQq7tGL1JKbxT83OIzNk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
conda_forge_output_validation: true
