travis:
  secure:
    BINSTAR_TOKEN: QUF//1NSU4dD7gg4fov5dICPGfd2ihRUSFf/Cew8D8ujv5w/tWoAG+1xMiFc85/opo7si8m+SirseM0knbWui0H7mdJinFV1pS6JDXmmbsutyeZP6RcWlftSd/iBIlFr8q4uQoECMto2NQrxvsU8oU0cHPFYyhXU3P12kfrgB4/yQx083+UBoNkDtF3xHhm5aWN8diBuwCYY1sZGcCKyVmJ1W2zphQuwo+cUAcpHOA99OL9NrPcY79ArN5IyIvAPxvoADsFHAyA/3syq0XIrZJAQRlk28j/6PzlgC3GxZbYHQGfHc6U5IIMzw1j1xUNtZ4LjHd6Gr1ito422h+gQagZeshvpDR0CIi009bI1ZGjf4QYD6dhCL1VNBkvOzSa8Mjq9coEgGkICdi3FRm5e2W7I8nduBLht4dpurQG23EcE+Rr2gtpY+JHPg17fcNTvdx1FYGtLr1+a2yRCwtHbGMp15fr+YggBS9Oec833yqWK8n71+7SmMEklsZjkbhsZhW7E7dy/GfNwSkHpIohVJbeWkKJ+cVJbE0WtiGZR2V9Vdmi7H3rXPKZJEE25WXHWMNYIKLNvVZ7jGjM6k4O3Isn7R6ELP38p/c50GOiLbKUIs21h0haFiPfleD0BHWD9c5+K5VnEDqmc0mcFLQr5gF9ggm/n/rbrd3njN99pgig=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
