travis:
  secure:
    BINSTAR_TOKEN: RrcoOLbnwnjyGT+GGUmCrduR0Z8zoa5T7R0u/+OZyu5VByHnVF8QWrA3qoC3f+LhcCUHujgthFz8RSZvdNQyeFerjM545g4Zzsu97xeRcS2YX/XHK81i6HmcGMcx8Mo1XTwMfi+aa6JghCsh69uiyC51yuuIErh23eYWjhSYWkfG1he3fhd3Rq6iRtpeltaP2XWuxKHzpNxXmlue0fhf6zvx5ph3mDkI5TeRaOyMl9wwTwlf5WyqRC0eLRjulRQN65ympqlh6N/Z0PBRvSyq8BerxXaBOndkWSd8PG5BLCqLDlKmBTMWsWNqIF2/QV3FdOiwz3fGvd+l8f5tMvtC7Tt7FSFrzLp9QbPCIgGxCRqtJYqSdv6ebzYDesAmUQrzS67EvcMrzl426Q4K8s91qrxfeGcqQIXx7+3Iwwsx4bdb7i4RmcsO6Wyb3aHlZDu7CC/TScSRxjyZUktcdT/vZoRc8JFP+BZucqDcpsUj0BYJjth6BT7Ph2/ghLVpj0PhLSlxuRookr+gTNCRrOgRkk+IqE9vPuvYll9Saw4CaCPOrvOFRmsMO0vkK/9KKdKjRWbzm1TchARLsMPz3rP32fwLRmQ8HnmBCYmkx2j1ZwYKaXVSnE3K29x0R+Eg3CaMYNOOUsjfCuIrI/akMT9ZgmPetlo5VaVnpcF9k3ff9yg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
